import React from 'react';
import { useParams } from 'react-router-dom';
import EthnicGroupInfo from './dantocInfo.js';
import MultiLevelNavbar from '../components/Navbar.js';
import Footer from '../components/Footer.js';

// Data cho tất cả các dân tộc
export const ethnicData = {
  1: {
    name: 'Cống',
    selfName: 'Cống',
    otherName: 'Xắm khống, Phuy A',
    localGroup: 'Không có',
    region: 'Tây Bắc Bộ',
    area: 'Huyện Mường Tè, tỉnh Lai Châu',
    population: '2.729',
    populationPercent: '0.003%',
    languageGroup: 'Tạng - Miến',
    languageFamily: 'Hán - Tạng',
    shortHistory: 'Người Cống di cư từ Lào sang Việt Nam. Họ sống nhờ làm nương và hái lượm. Người Cống không dệt vải mà chỉ trồng bông và trao đổi với các dân tộc khác. Chiếc áo truyền thống của người phụ nữ Cống đặc trưng bởi hai ống tay áo được trang trí bởi những mảng màu xanh, đỏ, vàng, trắng xếp xen kẽ. Váy của người Cống cùng kiểu với váy của người Thái, nhưng có nhiều hoa văn dệt dọc theo thân váy.',
    image1: 'Cong-W.png',
    image2: 'Cong-M.png',
  },
  2: {
    name: 'Hà Nhì',
    selfName: 'Hà Nhi gia',
    otherName: 'U Ní, Xá U Ní',
    localGroup: 'Hà Nhì, Cồ Chồ, Hà Nhì La Mí, Hà Nhì đen',
    region: 'Tây Bắc Bộ',
    area: 'Tỉnh Lai Châu và tỉnh Lào Cai',
    population: '25.539',
    populationPercent: '0.027%',
    languageGroup: 'Tạng - Miến',
    languageFamily: 'Hán - Tạng',
    shortHistory: 'Từ thế kỷ VIII, thư tịch cổ đã ghi nhận sự có mặt của người Hà Nhì ở Tây Bắc Việt Nam. Nhưng phần lớn người Hà Nhì hiện tại là con cháu của thế hệ Hà Nhì di cư từ Trung Quốc sang Việt Nam khoảng thế kỷ XVIII. Người Hà Nhì giỏi làm ruộng bậc thang, biết tận dụng các loại phân bón và thủy lợi. Trang phục phụ nữ Hà Nhì Hoa chủ đạo là màu đỏ, đội mũ có nhiều tua rua sặc sỡ. Trang phục phụ nữ Hà Nhì Đen có màu đen là chủ đạo, trang trí bằng các hoa văn trắng hoặc xanh tinh tế. Phụ nữ Hà Nhì Đen khi lấy chồng sẽ bện tóc cùng tóc giả rồi vấn quanh đầu, rồi mới đội khăn.',
    image1: 'HaNhi-W.png',
    image2: 'HaNhi-M.png',
  },
  3: {
    name: 'Kháng',
    selfName: 'Mơ Kháng',
    otherName: 'Xá Khao, Xá Xúa, Xá Đôn, Xá Dâng, Xá Hộc,Xá Ái, Xá Bung, Quảng Lâm',
    localGroup: 'Kháng Dẩng, Kháng Hoặc, Kháng Dón, Kháng Súa, Ma Háng, Bư Háng, Ma Háng Bẻng, Bư Háng Cọi',
    region: 'Tây Bắc Bộ',
    area: 'Tỉnh Sơn La, Lai Châu và Điện Biên',
    population: '16.180',
    populationPercent: '0.017%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Kháng trồng lúa nếp làm cây lương thực chính. Họ có nghề đan lát và chế thuyền độc mộc. Người Kháng thường đổi bông lấy vải vóc, quần áo của người Thái. Trang phục truyền thống của hai dân tộc vì thế khá giống nhau. Phụ nữ Kháng quấn khăn nhuộm chàm, hai đầu khăn có đính tua chỉ hoặc tua len. Khăn piêu cũng được người Kháng sử dụng, kiểu dáng giống người Thái nhưng hoa văn có một chút khác biệt.',
    image1: 'Khang-W.png',
    image2: 'Khang-M.png',
  },
  4: {
    name: 'Khơ Mú',
    selfName: 'Kmụ, Kưm Mụ',
    otherName: 'Xá Cẩu, Khạ Klẩu, Mãng Cẩu, Tày Hạy, Mứn Xen, Pu Thềnh, Tềnh.',
    localGroup: 'Không có',
    region: 'Tây Bắc Bộ',
    area: 'Các tỉnh Yên Bái, Sơn La, Lai Châu',
    population: '90.612',
    populationPercent: '0.094%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Khơ Mú là một trong những dân tộc lâu đời nhất ở vùng Tây Bắc Việt Nam. Họ chủ sống canh tác bằng hình thức du canh, du cư nương rẫy nên còn được gọi bằng biệt danh "Xá ăn lửa". Hình thức trao đổi chủ yếu là hàng đổi hàng, có vỏ ốc "kxoong" là vật ngang giá (tương tự tiền.)Trang phục truyền thống của phụ nữ Khơ Mú gồm khăn piêu đen đội đầu, áo "cỏm" đen có hàng cúc hình chữ nhật (pam) hoặc hình bướm (pem) ở ngực, dây lưng, váy, xà cạp, cài đầu, xà tích... Ngày nay khăn piêu Khơ Mú có thể có thêm hoa văn chỉ thêu sặc sỡ do giao lưu văn hóa với người Thái. Nam giới mặc quần áo chàm, thường đội mũ nồi.',
    image1: 'KhoMu-W.png',
    image2: 'KhoMu-M.png',
  },
  5: {
    name: 'La Ha',
    selfName: 'La Ha, Klá, Phlạo',
    otherName: 'Xá Cha, Xá Bung, Xá Khao, Xá Táu Nhạ, Xá Poọng, Xá Uống, Bủ Hà, Pụa.',
    localGroup: 'La Ha cạn (Khlá Phlao), La Ha nước (La Ha củng)',
    region: 'Tây Bắc Bộ',
    area: 'Tỉnh Sơn La và Lào Cai',
    population: '10.157',
    populationPercent: '0.011%',
    languageGroup: 'Ka Đai',
    languageFamily: 'Thái-Ka Đai',
    shortHistory: 'Người La Ha xuất hiện ở khu vực Tây Bắc nước ta từ lâu đời, khoảng trước thế kỷ XI-XII. Người La Ha không có nghề trồng bông dệt vải, phần lớn đồ mặc của họ là do trao đổi với người Thái mà có. Trang phục người La Ha giống với người Thái Đen.',
    image1: 'Laha-W.png',
    image2: 'Laha-M.png',
  },
  6: {
    name: 'La Hủ',
    selfName: 'La Hủ',
    otherName: 'Xá lá vàng, Cò Xung, Khù Sung, Kha Quy, Cọ Sọ, Nê Thú',
    localGroup: 'La Hủ na (đen), La Hủ sư (vàng) và La Hủ phung (trắng).',
    region: 'Tây Bắc Bộ',
    area: 'Tỉnh lai Châu',
    population: '12.113',
    populationPercent: '0.013%',
    languageGroup: 'Tạng - Miến',
    languageFamily: 'Hán - Tạng',
    shortHistory: 'Người La Hủ nổi tiếng với nghề đan lát và nghề rèn. Họ không trồng bông mà thường đổi vật phẩm cho các dân tộc khác để lấy bông hoặc vải. Phụ nữ mặc quần áo dài, áo cài khuy bên nách. Trang phục phụ nữ có nhiều tua chỉ màu trên khăn, nhiều đồng xu đính trên áo và tay áo gồm nhiều mảnh vải màu ghép lại. Nam giới mặc trang phục tương tự nhiều dân tộc khác vùng Tây Bắc, với quần áo màu chàm, áo năm thân xẻ nách và xẻ ngực, cài bằng nút vải.',
    image1: 'LaHu-W.png',
    image2: 'LaHu-M.png',
  },
  7: {
    name: 'Lào',
    selfName: 'Thay, Thay Duồn, Thay Nhuồn',
    otherName: 'Phu Thay, Phu Lào',
    localGroup: 'Lào Bốc (Lào Cạn) và Lào Nọi (Lào Nhỏ)',
    region: 'Tây Bắc Bộ',
    area: 'Tỉnh Điện Biên, tỉnh Sơn La, tỉnh Lào Cai',
    population: '17.532',
    populationPercent: '0.018%',
    languageGroup: 'Tày - Thái',
    languageFamily: 'Thái - Ka Đai',
    shortHistory: 'Người Lào tại Việt Nam có nguồn gốc di cư từ nước Lào. Họ đặc biệt phát triển tiểu thủ công nghiệp. Nghề gốm, nghề dệt thổ cẩm, nghề rèn, chạm bạc đều có những sản phẩm giá trị cao. Người Lào ở Lai Châu được gọi là Lào Lự do ăn mặc khá giống người Lự. Phụ nữ Lào mặc váy thắt ngang ngực, dài đến bắp chân. Gấu váy có nhiều hoa văn sặc sỡ. Trang phục nam khá giống người Thái',
    image1: 'Lao-W.png',
    image2: 'Lao-M.png',
  },
  8: {
    name: 'Lự',
    selfName: 'Lừ, Thay hoặc Thay Lừ',
    otherName: 'Phù Lừ, Nhuồn, Duồn',
    localGroup: 'Lự Đen (Lừ Đăm)',
    region: 'Tây Bắc Bộ',
    area: 'Tỉnh Lai Châu và tỉnh Thái Nguyên',
    population: '6.757',
    populationPercent: '0.007%',
    languageGroup: 'Tày - Thái',
    languageFamily: 'Thái - Ka Đai',
    shortHistory: 'Người Lự đã sinh sống ở khu vực Điện Biên từ trước thế kỷ XI - XII. Họ phát triển nghề dệt và có nghề làm gươm nổi tiếng. Phụ nữ Lự mặc áo chàm xẻ ngực, mặc váy đen thêu trang trí. Họ đội khăn đầu màu đen, có 18 đường kẻ trắng trang trí, hai đầu có tua rua. Đàn ông Lự mặc áo chàm đen, áo cánh xẻ ngực cài cúc, quần từ đầu gối trở xuống có hoa văn. Họ đội khăn đen, trang trí sọc trắng, cuốn nhiều vòng quanh đầu.',
    image1: 'Lu-W.png',
    image2: 'Lu-M.png',
  },
  9: {
    name: 'Mảng',
    selfName: 'Mảng',
    otherName: 'Mảng Ư, Xá Mảng, Niểng O, Xá Bá O',
    localGroup: 'Mảng Gừng, Mảng Hệ',
    region: 'Tây Bắc Bộ',
    area: 'Tỉnh Lai Châu',
    population: '4.650',
    populationPercent: '0.005%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Mảng có tập tính du canh du cư, không phát triển chăn nuôi hay tiểu thủ công nghiệp. Phụ nữ Mảng mặc áo cánh xẻ ngực cùng váy dài và quấn một tấm vải trắng có hoa văn trang trí ngang thân. Nam mặc áo cánh xẻ ngực với quần',
    image1: 'Mang-W.png',
    image2: 'Mang-M.png',
  },
  10: {
    name: 'Si La',
    selfName: 'Cù Dề Sừ',
    otherName: 'Kha Pẻ',
    localGroup: 'Không có',
    region: 'Tây Bắc Bộ',
    area: 'Tỉnh Lai Châu',
    population: '909',
    populationPercent: '0.001%',
    languageGroup: 'Tạng - Miến',
    languageFamily: 'Hán - Tạng',
    shortHistory: 'Nguồn lương thực chính của người Si La là lúa, ngô trên nương. Nhìn chung mức sống của họ còn thấp, tử suất cao. Theo truyền thống, phụ nữ Si La mặc váy chàm, áo cài khuy bên nách phải, đặc biệt vạt ngực gắn đầy những đồng xu bạc, nhôm lấp lánh, cổ và tay áo trang trí bằng những đường vải nhiều màu. Phụ kiện có khăn đội đầu và chiếc túi được trang trí bằng chỉ đỏ sặc sỡ. Nam mặc áo ngắn xẻ ngực, quần rộng.',
    image1: 'SiLa-W.png',
    image2: 'SiLa-M.png',
  },
  11: {
    name: 'Xinh Mun',
    selfName: 'Xinh-mun',
    otherName: 'Puộc, Xá, Pnạ',
    localGroup: 'Xinh Mun Dạ, Xinh Mun Nghẹt',
    region: 'Tây Bắc Bộ',
    area: 'Đa phần ở tỉnh Sơn La. Một số ở Điện Biên',
    population: '29.503',
    populationPercent: '0.031%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Xinh Mun cư trú lâu đời ở khu vực Tây Bắc Việt Nam. Họ chịu nhiều ảnh hưởng của văn hóa Thái. Phụ nữ Xinh Mun mặc áo ngắn, có hàng khuy mở phía trước ngực. Khuy áo có thể có hình con cà cuống, con nhện hoặc con ve sầu. Váy họ mặc thường màu đen hoặc chàm, ngắn hở bắp chân. Về cơ bản trang phục người Xinh Mun giống người Thái Đen, nhưng cách đội khăn trên đầu có một chút khác biệt.',
    image1: 'XinhMun-W.png',
    image2: 'XinhMun-M.png',
  },
  12: {
    name: 'Bố Y',
    selfName: 'Bố Y',
    otherName: 'Chủng Chá, Trọng Gia',
    localGroup: 'Bố Y và Tu Dí',
    region: 'Tây Bắc Bộ, Đông Bắc Bộ',
    area: 'Quản Bạ (Hà Giang) và Mường Khương (Lào Cai)',
    population: '3.232',
    populationPercent: '0.003%',
    languageGroup: 'Tày - Thái',
    languageFamily: 'Thái - Ka Đai, Hán Tạng',
    shortHistory: 'Người Bố Y có nguồn gốc từ Trung Quốc, di cư sang Việt Nam khoảng hơn 150 năm trước. Người Bố Y mặc áo ngắn năm thân có ống tay rời, xiêm che ngực và bụng. Hoa văn trên vải được tạo thành bằng cách bôi sáp ong lên rồi nhuộm chàm. Tóc người phụ nữ được búi ngược lên đỉnh đầu, đội khăn chàm có thêu hoa văn bằng chỉ màu.',
    image1: 'BoY-W.png',
    image2: 'BoY-M.png',
  },
  13: {
    name: 'Dao',
    selfName: 'Kìm Mùn, Kìm Miền',
    otherName: 'Mán',
    localGroup: 'Dao Đỏ, Dao Quần chẹt, Dao Lô gang, Dao Tiền, Dao Quần trắng, Dao Thanh Y, Dao Làn Tẻn',
    region: 'Tây Bắc Bộ, Đông Bắc Bộ',
    area: 'Trải rộng ở khu vực phía Bắc Việt Nam, từ Cao Bằng, Lào Cai, Hà Giang…đến Vĩnh Phúc, Hòa Bình.',
    population: '891.151',
    populationPercent: '0.926%',
    languageGroup: 'Dao',
    languageFamily: 'Mông - Dao',
    shortHistory: 'Người Dao di cư từ Trung Quốc sang Việt Nam từ khoảng thế kỷ XII - XIII đến nửa đầu thế kỷ XX. Họ phát triển nghề trồng bông, dệt vải, nghề rèn và nghề bạc. Về ăn mặc, mỗi nhóm Dao có cách ăn mặc và bản sắc văn hóa vô cùng khác biệt. Với người Dao Đỏ, màu chủ đạo trong trang phục là màu đỏ, với nhiều hoa văn thêu tay, tua đỏ và chuỗi hạt cườm rực rỡ. Họ quan niệm màu đỏ mang lại hạnh phúc và may mắn.',
    image1: 'Dao-W.png',
    image2: 'Dao-M.png',
  },
  14: {
    name: 'Giáy',
    selfName: 'Giáy',
    otherName: 'Nhắng, Giẳng',
    localGroup: 'Không có',
    region: 'Tây Bắc Bộ, Đông Bắc Bộ',
    area: 'Một số huyện thuộc tỉnh Lào Cai, Hà Giang và Lai Châu',
    population: '67.858',
    populationPercent: '0.071%',
    languageGroup: 'Tiếng Giáy',
    languageFamily: 'Thái - Ka Đai',
    shortHistory: 'Người Giáy di cư từ Trung Quốc sang Việt Nam khoảng đầu thế kỷ XIX. Họ có nhiều kinh nghiệm canh tác ruộng bậc thang, trồng lúa nước và nhiều loại cây lương thực khác. So với các dân tộc Tây Bắc khác, trang phục truyền thống người Giáy khá đơn giản. Phụ nữ Giáy mặc áo năm thân với vải nền sặc sỡ màu đỏ, hồng hay xanh... Viền cổ tay và viền áo được trang trí với những đường vải khác màu nổi bật. Phụ kiện đi kèm thường là những chiếc khăn vuông dệt nhiều màu sắc được dệt từ len.',
    image1: 'Giay-W.png',
    image2: 'Giay-M.png',
  },
  15: {
    name: 'Mông',
    selfName: 'Mông, Na Miẻo',
    otherName: 'Mẹo, Mèo, Miếu Hạ, Mán Trắng',
    localGroup: 'Mông Trắng, Mông Hoa, Mông Ðỏ, Mông Ðen, Mông Xanh, Na Miẻo',
    region: 'Tây Bắc Bộ, Đông Bắc Bộ',
    area: 'Tập trung ở các tỉnh Đông và Tây Bắc: Hà Giang, Lào Cai, Lai Châu, Sơn La. Một bộ phận ở Gia Lai và Kon Tum.',
    population: '1.393.547',
    populationPercent: '1.448%',
    languageGroup: 'Mông',
    languageFamily: 'Mông-Dao',
    shortHistory: 'Người Mông có truyền thống trồng xen canh trên nương. Họ phát triển nghề đan lát, rèn, làm yên cương ngựa, làm gỗ, làm giấy, đồ bạc, đặc biệt là dệt vải từ cây lanh. Trang phục người Mông khá khác biệt giữa các nhóm. Phụ nữ Mông Hoa mặc váy chàm có hoa văn tạo thành bằng sáp ong, áo xẻ nách, vai và ngực có đắp vải màu. Họ thường để tóc dài và vấn quanh đầu cùng với tóc giả. Nam người Mông mặc quần đen ống rộng để dễ leo đồi núi và múa khèn.',
    image1: 'Mong-W.png',
    image2: 'Mong-M.png',
  },
  16: {
    name: 'Phù Lá',
    selfName: 'Lao Va Xơ, Bồ Khô Pạ, Phù Lá',
    otherName: 'Xá Phó, Cần Thin',
    localGroup: 'Phù Lá Lão - Bồ Khô Pạ, Phù Lá Ðen, Phù Lá Hán',
    region: 'Tây Bắc Bộ, Đông Bắc Bộ',
    area: 'Tỉnh Hà Giang, Lào Cai, Yên Bái, Lai Châu',
    population: '12.471',
    populationPercent: '0.013%',
    languageGroup: 'Tạng - Miến',
    languageFamily: 'Hán - Tạng',
    shortHistory: 'Nhóm Phù Lá Lão - Bồ Khô Pạ có mặt ở khu vực Tây Bắc Việt Nam từ lâu đời, các nhóm khác mới xuất hiện trong khoảng 200-300 năm. Phụ nữ nhóm Phù Lá Lão mặc váy cùng với với áo ngắn chui đầu, cổ vuông. Trên trang phục được trang trí bằng hình thêu, hạt cườm và vỏ ốc núi. Nam giới mặc quần rộng cùng áo chàm đen, sau lưng áo đính nhiều hạt cườm lấp lánh. Các nhóm Phù Lá khác phụ nữ mặc quần cùng với áo dài xẻ ngực hoặc áo ngắn xẻ nách.',
    image1: 'PhuLa-W.png',
    image2: 'PhuLa-M.png',
  },
  17: {
    name: 'Thái',
    selfName: 'Tay, Tày hoặc Thay',
    otherName: 'Tay Thanh, Man Thanh, Tay Mười, Tày Mường, Hàng Tổng, Tay Dọ, Thổ.',
    localGroup: 'Thái Ðen (Tày Ðăm), Thái Trắng (Tày Ðón /Tày Khao) Thái Đỏ (Tày Đèng)',
    region: 'Tây Bắc Bộ, Bắc Trung Bộ',
    area: 'Tỉnh Hòa Bình, Lai Châu, Điện Biên, Sơn La, Lào Cai, Yên Bái, Thanh Hóa, Nghệ An',
    population: '1.820.950',
    populationPercent: '1.893%',
    languageGroup: 'Tày - Thái',
    languageFamily: 'Thái - Ka Đai',
    shortHistory: 'Người Thái có nguồn gốc Đông Nam Á lục địa, họ có mặt ở khu vực Việt Nam từ hơn 1200 năm trước. Người Thái phát triển nghề trồng lúa nước trong các cánh đồng thung lũng. Họ còn trồng nhiều cây lương thực khác, và trồng bông để dệt vải. Phụ nữ Thái mặc áo cánh ngắn đủ màu sắc, trên đường nẹp xẻ ngực có đính khuy bạc hình bướm, nhện hay ve sầu. Nhóm Thái Đen đội khăn piêu có nhiều hoa văn rực rỡ. Đàn ông người Thái mặc áo cánh xẻ ngực có túi, cuốn khăn đen mỏ rìu. Ngày lễ đàn ông mặc áo đen dài xẻ nách, cuốn ngăn dài một sải tay.',
    image1: 'Thai-W.png',
    image2: 'Thai-M.png',
  },
  18: {
    name: 'Cờ Lao',
    selfName: 'Cờ Lao',
    otherName: 'Tứ Ðư, Ho Ki, Voa Ðề',
    localGroup: 'Cờ Lao Xanh, Cờ Lao Trắng, Cờ Lao Ðỏ',
    region: 'Đông Bắc Bộ',
    area: 'Tỉnh Hà Giang, tỉnh Tuyên Quang',
    population: '4.003',
    populationPercent: '0.004%',
    languageGroup: 'Tiếng Cờ Lao',
    languageFamily: 'Thái - Ka Đai',
    shortHistory: 'Người Cờ Lao chuyển cư vào Việt Nam khoảng 150-200 năm trước. Họ sống chủ yếu nhờ làm ruộng nương rẫy. Nghề đan lát và làm gỗ phát triển. Phụ nữ Cờ Lao mặc áo dài đến gối (giống với áo của người Nùng, Giáy), trên ngực và tay áo có đắp những miếng vải màu.',
    image1: 'CoLao-W.png',
    image2: 'CoLao-M.png',
  },
  19: {
    name: 'La Chí',
    selfName: 'Cù tê',
    otherName: 'Thổ Ðen, Mán, Xá, La Quả',
    localGroup: 'Không có',
    region: 'Đông Bắc Bộ',
    area: 'Tỉnh Hà Giang và tỉnh Lào Cai',
    population: '15.126',
    populationPercent: '0.016%',
    languageGroup: 'Ka Đai',
    languageFamily: 'Thái - Ka Đai',
    shortHistory: 'Người La Chí giỏi canh tác ruộng bậc thang, trồng lúa nước. Đàn ông mặc áo dài năm thân, cài khuy bên nách phải, đội khăn cuốn hay khăn xếp. Phụ nữ mặc áo dài tứ thân, đeo yếm và thắt lưng vải. Ngày lễ tết, phụ nữ La Chí đội thêm một chiếc khăn trên đầu. Màu chủ đạo trong trang phục người La Chí là màu chàm đen.',
    image1: 'LaChi-W.png',
    image2: 'LaChi-M.png',
  },
  20: {
    name: 'Lô Lô',
    selfName: 'Lô Lô',
    otherName: 'Mùn Di, Di, Màn Di, La La, Qua La, Ô Man, Lu Lộc Màn',
    localGroup: 'Lô Lô Hoa và Lô Lô Đen',
    region: 'Đông Bắc Bộ',
    area: 'Tỉnh Hà Giang, Cao Bằng và Lào Cai',
    population: '4.827',
    populationPercent: '0.005%',
    languageGroup: 'Tạng - Miến',
    languageFamily: 'Hán - Tạng',
    shortHistory: 'Trang phục của hai nhóm Lô Lô Đen và Lô Lô Hoa đều trang trí bằng cách khâu các mảnh vải mầu lại với nhau. Phụ nữ Lô Lô Hoa mặc áo ngắn xẻ ngực, tay dài. Phần thân trước áo được phủ kín bởi các mảng màu hình tam giác ghép lại. Khăn đội trên đầu của phụ nữ cũng được trang trí bằng vải nhiều màu, hạt cườm và những chùm quả nhỏ đủ màu. Nam giới Lô Lô Hoa mặc áo cánh ngắn xẻ ngực, quần loe, đầu bít khăn sặc sỡ gần giống khăn phụ nữ.',
    image1: 'LoLo-W.png',
    image2: 'LoLo-M.png',
  },
  21: {
    name: 'Ngái',
    selfName: 'Sán Ngải',
    otherName: 'Ngái Hắc Cá, Ngái Lầu Mần, Hẹ, Sín, Ðản, Lê, Xuyến',
    localGroup: 'Không có',
    region: 'Đông Bắc Bộ',
    area: 'Tỉnh Bắc Giang, Cao Bằng, Lạng Sơn, Quảng Ninh',
    population: '1.649',
    populationPercent: '0.002%',
    languageGroup: 'Hán',
    languageFamily: 'Hán - Tạng',
    shortHistory: 'Người Ngái là một trong số ít dân tộc bị sụt giảm dân số mạnh, từ 4841 người (1999) xuống còn 1035 người (2009). Tuy hiện tại dân số đã tăng lên nhưng vẫn cần được các cơ quan chức năng lưu tâm. Người Ngái chủ yếu mặc trang phục bằng vải bông nhuộm chàm, gần như không có hoa văn. Nam giới mặc áo ngắn xẻ ngực cùng quần dài và thắt lưng. Nữ giới mặc áo năm thân xẻ dưới cổ, chéo qua nách phải.',
    image1: 'Ngai-W.png',
    image2: 'Ngai-M.png',
  },
  22: {
    name: 'Nùng',
    selfName: 'Nồng',
    otherName: '',
    localGroup: 'Nùng Giang, Nùng Xuồng, Nùng An, Nùng Inh, Nùng Lòi, Nùng Cháo, Nùng Phàn Slình, Nùng Quy Rịn, Nùng Dín',
    region: 'Đông Bắc Bộ',
    area: 'Các tỉnh Bắc và Đông Bắc Bộ: Lạng Sơn, Cao Bằng, Bắc Kạn, Thái Nguyên, Tuyên Quang…',
    population: '1.083.298',
    populationPercent: '1.126%',
    languageGroup: 'Tày - Thái',
    languageFamily: 'Thái - Ka Đai',
    shortHistory: 'Người Nùng có nguồn gốc từ Quảng Châu (Trung Quốc) di cư sang Việt Nam từ khoảng thế kỷ XVII-XIX. Người Nùng sống bằng trồng trọt trên nương rẫy. Họ phát triển nhiều nghề thủ công: dệt, rèn, làm ngói, làm giấy… Trang phục người Nùng chủ yếu bằng vải nhuộm chàm. Phụ nữ mặc áo năm thân tay rộng, cổ áo có những mảnh vải khác màu, đoạn cổ tay và lá sen có đắp một miếng vải. Đàn ông mặc áo cổ đứng, xẻ ngực, có hàng cúc vải.',
    image1: 'Nung-W.png',
    image2: 'Nung-M.png',
  },
  23: {
    name: 'Pà Thẻn',
    selfName: 'Pà Hưng',
    otherName: 'Mèo Lài, Mèo Hoa, Mèo Ðỏ, Bát tiên tộc...',
    localGroup: 'Không có',
    region: 'Đông Bắc Bộ',
    area: 'Tỉnh Hà Giang và tỉnh Tuyên Quang',
    population: '8.248',
    populationPercent: '0.009%',
    languageGroup: 'Hmong',
    languageFamily: 'Hmong - Dao',
    shortHistory: 'Theo truyền thuyết của người Pà Thẻn, khoảng thế kỷ XVII, tổ tiên họ di cư cùng với người Dao từ vùng Than Lô (Trung Quốc) vào Việt Nam qua đường biển. Người Pà Thẻn có nghề dệt được các dân tộc láng giềng ưa chuộng. Màu chủ đạo trong trang phục truyền thống của phụ nữ Pà Thẻn là màu đỏ - màu của con chim lửa trong đức tin của họ. Phụ nữ để tóc dài, vấn khăn quanh đầu, khăn có những chùm tua rua đỏ vàng. Áo phụ nữ không có cổ và khuy cài, thân sau dài hơn thân trước, gồm nhiều mảnh vải ghép công phu lại với nhau.',
    image1: 'PaThen-W.png',
    image2: 'PaThen-M.png',
  },
  24: {
    name: 'Pu Péo',
    selfName: 'Kabeo',
    otherName: 'La Quả, Penti Lô Lô',
    localGroup: 'Không có',
    region: 'Đông Bắc Bộ',
    area: 'Cao nguyên Đồng Văn tỉnh Hà Giang',
    population: '903',
    populationPercent: '0.001%',
    languageGroup: 'Ka Đai',
    languageFamily: 'Thái - Ka Đai',
    shortHistory: 'Dân tộc Pu Péo được ghi nhận là một trong những dân tộc khai khẩn đầu tiên ở khu vực Cực Bắc Việt Nam. Họ có kỹ thuật canh tác nông nghiệp tương đối cao. Thường ngày nam giới Pu Péo mặc áo cánh ngắn xẻ ngực màu chàm, quần lá tọa cùng màu. Dịp lễ, nam giới quấn khăn, mặc áo dài xẻ nách màu chàm hoặc trắng. Phụ nữ Pu Péo để tóc dài quấn quanh đầu, cài bằng lược hoặc đội khăn vuông ôm lấy tóc. Họ mặc hai lớp áo, áo ngoài xẻ ngực, tay áo, nẹp áo, gấu áo có nhiều hoa văn trang trí.',
    image1: 'PuPeo-W.png',
    image2: 'PuPeo-M.png',
  },
  25: {
    name: 'Sán Chay',
    selfName: 'Sán Chay',
    otherName: 'Hờn Bán, Chùng, Trại',
    localGroup: 'Cao Lan, Sán Chỉ',
    region: 'Đông Bắc Bộ',
    area: 'Tập trung ở đông bắc Bắc Bộ: Tuyên Quang, Thái Nguyên, Bắc Giang, rải rác ở các tỉnh Quảng Ninh, Cao Bằng, Lạng Sơn',
    population: '201.398',
    populationPercent: '0.209%',
    languageGroup: 'Cao Lan: Tày - Thái | Sán Chỉ: Hán',
    languageFamily: 'Thái - Ka Đai, Hán Tạng',
    shortHistory: 'Người Sán Chay sớm tiếp thu nền văn minh lúa nước, hay sinh sống quanh những nơi địa thế thấp, có thung lũng bằng để làm ruộng bậc thang. Phụ nữ Sán Chay mặc váy chàm, có hoa văn trang trí ở hò áo và lưng áo. Thường ngày họ đeo một chiếc thắt lưng chàm, ngày lễ đeo hai đến ba chiếc thắt lưng nhiều màu.',
    image1: 'SanChay-W.png',
    image2: 'SanChay-M.png',
  },
  26: {
    name: 'Sán Dìu',
    selfName: 'San Déo Nhín (Sơn Dao Nhân)',
    otherName: 'Trại, Trại Ðất, Mán Quần cộc, Mán Váy xẻ...',
    localGroup: 'Không có',
    region: 'Đông Bắc Bộ',
    area: 'Các tỉnh trung du Bắc Bộ: Thái Nguyên, Vĩnh Phúc, Bắc Giang, Quảng Ninh, Tuyên Quang, Hải Dương...',
    population: '183.004',
    populationPercent: '0.190%',
    languageGroup: 'Hán',
    languageFamily: 'Hán - Tạng',
    shortHistory: 'Người Sán Dìu có nguồn gốc từ Quảng Đông (Trung Quốc) thời nhà Minh, họ di cư vào Việt Nam khoảng 300 năm trước. Cây lương thực chủ yếu họ trồng là ngô. Bộ trang phục của phụ nữ Sán Dìu gồm có khăn đội đầu, áo dài ngang đầu gối, áo ngắn mặc trong, ngực đeo yếm trắng, váy xẻ nhiều lớp dài đến đầu gối, bắp chân cuốn xà cạp trắng và một chiếc thắt lưng lụa xanh hoặc đỏ. Trang phục đàn ông Sán Dìu thì khá đơn giản, áo kiểu bà ba, có túi rộng, quần ống rộng và cạp chun để tiện leo núi, làm nương.',
    image1: 'SanDiu-W.png',
    image2: 'SanDiu-M.png',
  },
  27: {
    name: 'Tày',
    selfName: 'Tày',
    otherName: 'Thổ',
    localGroup: 'Thổ, Ngạn, Phén, Thu Lao và Pa Dí',
    region: 'Đông Bắc Bộ',
    area: 'Vùng thung lũng các tỉnh Đông Bắc, từ Quảng Ninh, Bắc Giang đến Cao Bằng, Bắc Kạn, Lào Cai, Yên Bái',
    population: '1.845.492',
    populationPercent: '1.918%',
    languageGroup: 'Tày - Thái',
    languageFamily: 'Thái - Ka Đai',
    shortHistory: 'Người Tày xuất hiện ở Việt Nam từ khoảng nửa cuối thiên niên kỷ thứ nhất trước Công Nguyên. Họ phát triển nghề trồng lúa nước, biết thâm canh và sử dụng nhiều biện pháp thủy lợi. Nghề dệt thổ cẩm của người Tày đặc biệt phát triển, với nhiều hoa văn đẹp và độc đáo. Trang phục truyền thống người Tày bằng vải bông nhuộm chàm, gần như không thêu thùa, trang trí.',
    image1: 'Tay-W.png',
    image2: 'Tay-M.png',
  },
  28: {
    name: 'Mường',
    selfName: 'Mol (hoặc Mon, Moan, Mual)',
    otherName: 'Không có',
    localGroup: 'Ao Tá (Âu Tá)',
    region: 'Đồng bằng sông Hồng',
    area: 'Các tỉnh Hòa Bình, Thanh Hóa, Phú Thọ',
    population: '1.452.095',
    populationPercent: '1.509%',
    languageGroup: 'Việt - Mường',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Mường có cùng nguồn gốc với người Việt, họ xuất hiện ở khu vực miền Bắc nước ta từ lâu đời. Người Mường sống chủ yếu dựa vào ruộng nước, với lúa là cây lương thực chính. Phụ nữ và đàn ông Mường đều thích hút thuốc trong các ống điếu to. Y phục nam người Mường khá đơn giản với quần, thắt lưng, áo cánh ngắn may vải bông hoặc tơ tằm, cài khuy ngực hoặc cài chéo sang bên. Phụ nữ Mường đội trên đầu một chiếc khăn chữ nhật trắng không họa tiết, mặc áo cánh thân ngắn xẻ ngực, yếm, kèm theo váy dài đến mắt cá chân.',
    image1: 'Muong-W.png',
    image2: 'Muong-M.png',
  },
  29: {
    name: 'Kinh',
    selfName: 'Người Kinh',
    otherName: 'Việt, Người Việt',
    localGroup: 'Không có',
    region: 'Đồng bằng sông Hồng',
    area: 'Toàn quốc',
    population: '82,089,728',
    populationPercent: '85.32%',
    languageGroup: 'Việt-Mường',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Việt định cư từ lâu đời ở khu vực Bắc Bộ và Bắc Trung Bộ. Họ phát triển nền nông nghiệp lúa nước, thủy lợi từ rất sớm. Nhiều nghề thủ công cũng như hệ thống giao thương đều phát triển. Xưa, đàn ông Việt thường mặc quần chân chè, áo cánh màu sẫm, đi chân đất. Ngày lễ đàn ông mặc áo chùng lương đen, đội khăn xếp, đi guốc mộc. Đàn bà Việt thường mặc váy đen, áo cánh, chít khăn mỏ quạ. Ngày lễ phụ nữ mặc áo dài. Theo số liệu năm 2019, cơ cấu dân số Việt Nam bao gồm dân tộc Việt (chiếm 85,32%) và 53 dân tộc thiểu số.',
    image1: 'Kinh-W.png',
    image2: 'Kinh-M.png',
  },
  30: {
    name: 'Bru- Vân Kiều',
    selfName: 'Bru- Vân Kiều',
    otherName: 'Bru- Vân Kiều',
    localGroup: 'Vân Kiều, Trì, Khùa, Ma Coong.',
    region: 'Bắc Trung Bộ',
    area: 'vùng Trường Sơn - Tây Nguyên (Quảng Trị, Thừa Thiên- Huế, Quảng Bình)',
    population: '94.598',
    populationPercent: '0.098%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Bru- Vân Kiều là một trong những dân tộc cư trú lâu đời nhất ở khu vực Trường Sơn. Họ không phát triển nghề thủ công. Vải vóc phần lớn được mua từ Lào. Khi chưa có vải, quần áo được làm bằng vỏ cây Sui đập dập. Theo truyền thống, nam đóng khố, để tóc dài hoặc búi lên.Trang phục phụ nữ là ao xẻ ngực, nhuộm chàm đen, có trang trí hàng kim loại bạc hình tròn ở mép cổ và hai bên nẹp áo. Có nhóm mặc áo chui đầu không tay, cổ khoét hình tròn hoặc hình vuông. Thanh nữ búi tóc lệch sang bên trái, đàn bà có chồng búi trên đỉnh đầu.',
    image1: 'Bru-VanKieu-W.png',
    image2: 'Bru-VanKieu-M.png',
  },
  31: {
    name: 'Chứt',
    selfName: 'Chứt',
    otherName: 'Rục, Arem, Sách',
    localGroup: 'Mày, Rục, Sách, Arem, Mã Liềng',
    region: 'Bắc Trung Bộ',
    area: 'Huyện Bố Trạch và Quảng Trạch, tỉnh Quảng Bình',
    population: '7.513',
    populationPercent: '0.008%',
    languageGroup: 'Việt-Mường',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Chứt chủ yếu sống bằng săn bắt hái lượm hoặc nông nghiệp nương rẫy du canh (nhóm Sách). Cho đến năm 1954, nhiều nhóm người Chứt vẫn sống trong các hang đá.Họ không có nghề dệt và không có trang phục truyền thống. Trang phục của họ do trao đổi với cộng đồng người Việt và người Lào mà có. Nam cởi trần đóng khố, nữ mặc váy. Ngày nay tất cả người Chứt mặc như người Việt.',
    image1: 'Chut-W.png',
    image2: 'Chut-M.png',
  },
  32: {
    name: 'Cơ Tu',
    selfName: 'Cơ Tu',
    otherName: 'Ca Tu, Ka Tu',
    localGroup: 'Không có',
    region: 'Bắc Trung Bộ',
    area: 'Miền núi tây bắc tỉnh Quảng Nam, tây nam tỉnh Thừa Thiên Huế',
    population: '74.173',
    populationPercent: '0.077%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Cơ Tu sống chủ yếu nhờ săn bắt, hái lượm và đánh cá. Họ phát triển nghề dệt, đan lát và làm gốm. Trong cộng đồng Cơ Tu vẫn thông dụng hình thức trao đổi hàng hóa thay vì sử dụng tiền. Đàn ông Cơ Tu cởi trần đóng khố. Phụ nữ Cơ Tu mặc váy dài hoặc váy ngắn kèm áo không tay. Người Cơ Tu chuộng nhất y phục bằng vải dệt nền đen có hoa văn bằng chì, kế đến là hoa văn bằng cườm trắng.',
    image1: 'CoTu-W.png',
    image2: 'CoTu-M.png',
  },
  33: {
    name: 'Ơ Đu',
    selfName: 'Ơ Đu hoặc I Đu',
    otherName: 'Tày Hạt',
    localGroup: 'Không có',
    region: 'Bắc Trung Bộ',
    area: 'Huyện Tương Dương tỉnh Nghệ An',
    population: '428',
    populationPercent: '0.0004%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Ơ Đu xưa tập trung dọc theo sông Nậm Nơn (huyện Tương Dương - tỉnh Nghệ An), sau do nhiều biến cố đã tản mát đi nhiều nơi. Người Ơ Đu có truyền thống tự dệt vải và may quần áo cho mình. Đàn ông mặc áo tơ tằm màu đỏ nhạt, cổ tròn, xẻ ngực và buộc dây. Phụ nữ mặc áo màu đen, tay dài, không khuy không cúc mà dùng dây buộc chéo. Trang phục của người Ơ Đu gần như không có hoa văn trang trí.',
    image1: 'ODu-W.png',
    image2: 'ODu-M.png',
  },
  34: {
    name: 'Tà Ôi',
    selfName: 'Tà-ôi',
    otherName: 'Tà Ôi, Pa Cô, Tà Uốt, KanTua, Pa Hy…',
    localGroup: 'Tà Ôi, Pa Cô, Pa Hy',
    region: 'Bắc Trung Bộ',
    area: 'Tỉnh Thừa Thiên Huế và tỉnh Quảng Trị',
    population: '52.356',
    populationPercent: '0.054%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Tà Ôi xuất hiện lâu đời ở Trường Sơn. Họ sống bằng trồng lúa rẫy kết hợp săn bắt hái lượm. Nghề dệt chỉ có ở một số nơi, và được các dân tộc lân cận khá ưa chuộng. Phụ nữ Tà Ôi mặc váy ống loại ngắn kèm áo, hoặc váy dài che từ ngực trở xuống. Ngày nay váy áo thường được dệt bằng sợi thổ cẩm đính với hạt cườm. Đàn ông Tà Ôi ngày thường đóng khố, cởi trần hoặc mặc áo chui đầu không tay. Trong những ngày se lạnh hoặc lễ hội, họ quấn tấm choàng hình chữ X trước ngực.',
    image1: 'TaOi-W.png',
    image2: 'TaOi-M.png',
  },
  35: {
    name: 'Thổ',
    selfName: 'Thổ',
    otherName: 'Người Nhà làng, Mường, Con Kha, Xá Lá Vàng',
    localGroup: 'Kẹo, Mọn, Cuối, Họ, Ðan Lai, Ly Hà, Tày Poọng',
    region: 'Bắc Trung Bộ',
    area: 'Phía tây tỉnh Nghệ An',
    population: '91.430',
    populationPercent: '0.095%',
    languageGroup: 'Việt - Mường',
    languageFamily: 'Nam Á',
    shortHistory: 'Cộng đồng người Thổ được tạo thành trong thế kỷ XIX bởi những người Việt, người Mường di cư và dân địa phương. Vì vậy các nhóm Thổ khác nhau có hệ thống tiếng nói và tập quán khá đa dạng. Ngày thường, phụ nữ Thổ thường mặc áo cánh trắng cổ viền, tay hẹp, đội khăn vuông trắng (một số nhóm mặc áo màu chàm). Khăn tang của người Mường cũng là màu trắng nhưng dài hơn. Đàn ông Thổ mặc quần trắng cạp vấn, áo dài lương đen và đầu đội khăn nhiễu.',
    image1: 'Tho-W.png',
    image2: 'Tho-M.png',
  },
  36: {
    name: 'Co',
    selfName: 'Cor hoặc Col',
    otherName: 'Cua, Trầu',
    localGroup: 'Không có',
    region: 'Nam Trung Bộ',
    area: 'Phía tây bắc tỉnh Quảng Ngãi và tây nam tỉnh Quảng Nam',
    population: '40.442',
    populationPercent: '0.042%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Đảo',
    shortHistory: 'Người Co chủ yếu sống bằng kinh tế rẫy. Nghề dệt và nghề rèn không phát triển nhưng họ lại có nhiều đồ đan đẹp. Người Cor chủ yếu mua vải từ người Việt và người Xơ Đăng. Ngày thường, đàn ông người Co cởi trần đóng khố. Phụ nữ mặc áo yếm hoặc áo cộc tay kèm váy. Ngày lễ, đàn ông đóng khố, mặc xà pôn (một tấm thổ cẩm rộng phủ kín đến bắp chân). Trang phục lễ của phụ nữ người Co rất rực rỡ, gồm nhiều chuỗi cườm ngũ sắc và các tua màu.',
    image1: 'Co-W.png',
    image2: 'Co-M.png',
  },
  37: {
    name: 'Ra Glai',
    selfName: 'Ra Glai',
    otherName: 'Raglai, Ra Glây, Raglay, Rang Chơk, Rang ngok',
    localGroup: 'Rai, La Oang',
    region: 'Nam Trung Bộ',
    area: 'Chủ yếu ở tỉnh Ninh Thuận, phía nam tỉnh Khánh Hòa và tỉnh Bình Thuận',
    population: '146.613',
    populationPercent: '0.152%',
    languageGroup: 'Mã Lai - Đa Đảo',
    languageFamily: 'Nam Đảo',
    shortHistory: 'Người Raglai có chiếc áo khoang - thân áo và ống tay áo có nhiều khoang đen trắng xen kẽ nhau. Người nam Raglai đeo khố, mặc áo khoang. Cả nam và nữ đều có khăn vấn đầu.',
    image1: 'RagLai-W.png',
    image2: 'RagLai-M.png',
  },
  38: {
    name: 'Brâu',
    selfName: 'Brâu',
    otherName: 'Brao',
    localGroup: 'Không có',
    region: 'Tây Nguyên',
    area: 'làng Ðắc Mế xã Bờ Y thuộc huyện Ngọc Hồi tỉnh Kon Tum',
    population: '525',
    populationPercent: '0.001%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Brâu di cư vào Việt Nam khoảng 100 năm trước, từ khu vực Nam Lào và Đông Bắc Campuchia. Đàn ông xưa đóng khố, đàn bà quấn váy tấm. Mùa hè, nam nữ thường ở trần hoặc mặc áo cánh ngắn chui đầu. Mùa lạnh thường khoác thêm một tấm mền. Nữ giới có tục căng tai để đeo những khoanh nứa vàng hoặc khuyên bằng ngà voi.',
    image1: 'Brau-W.png',
    image2: 'Brau-M.png',
  },
  39: {
    name: 'Chu ru',
    selfName: 'Chu-ru',
    otherName: 'Chơ Ru, Kru, Thượng',
    localGroup: 'Không có',
    region: 'Tây Nguyên',
    area: 'Các huyện Đơn Dương, Đức Trọng và Di Linh, tỉnh Lâm Đồng. Huyện An Sơn và Đức Linh tỉnh Ninh Thuận.',
    population: '23.242',
    populationPercent: '0.024%',
    languageGroup: 'Mã Lai - Đa Đảo',
    languageFamily: 'Nam Đảo',
    shortHistory: 'Có giả thuyết rằng xưa kia người Chu Ru là một phần của cộng đồng Chăm, xong tách ra sống biệt lập. Người Chu Ru phát triển nghề nông nghiệp, không phát triển nghề thủ công. Chủ yếu trang phục của họ là do trao đổi với các dân tộc láng giềng như Chăm, Cơ Ho, Raglai, Mạ...',
    image1: 'ChuRu-W.png',
    image2: 'ChuRu-M.png',
  },
  40: {
    name: 'Cơ Ho',
    selfName: 'Cơ Ho',
    otherName: '',
    localGroup: 'Xrê, Nộp (Tu nốp), Cơ Dòn, Chil, Lát (Lách), Tơ Ring (Tring)',
    region: 'Tây Nguyên',
    area: 'Lâm Đồng',
    population: '200.800',
    populationPercent: '0.209%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Cơ Ho sống bằng làm ruộng nước hoặc làm rẫy du canh với các dụng cụ nông nghiệp đặc trưng. Nghề dệt của người Cơ Ho đặc biệt phát triển. Nam giới đeo khố rộng bản, mặc áo chui đầu, không có tay áo. Phụ nữ mặc váy dệt thổ cẩm. Người Cơ Ho ưa dùng vải màu trầm, đặc biệt là màu xanh và xanh đen.',
    image1: 'CoHo-W.png',
    image2: 'CoHo-M.png',
  },
  41: {
    name: 'Ê đê',
    selfName: 'Anak Ea Đê, Ra Đê (hay Khaděl, Ê Đê, Êgar, Đê)',
    otherName: '',
    localGroup: 'Kpă, Adham, Krung, Mdhur, Ktul, Dilê, Hruê, Bíh, Biô, Kah, Kdrao, Dong Kay, Dong Mak, Ening, Arul, Hwing',
    region: 'Tây Nguyên',
    area: 'Đắc Lắc, phía nam Gia Lai và miền tây Phú Yên, Khánh Hòa',
    population: '398.671',
    populationPercent: '0.414%',
    languageGroup: 'Mã Lai - Đa Đảo',
    languageFamily: 'Nam Đảo',
    shortHistory: 'Người Ê Đê có nguồn gốc hải đảo, đã có mặt ở miền Trung Việt Nam từ lâu đời. Nghề thủ công phát triển là nghề đan lát mây tre và trồng bông, dệt vài kiểu nguyên thủy. Phụ nữ Ê Đê cuốn váy tấm dài đến gót, mùa hè ở trần hoặc mặc áo ngắn chui đầu. Đàn ông đóng khố, mặc áo cánh chui đầu. Nam nữ đều có tục cà răng - căng tai và nhuộm đen răng.',
    image1: 'EDe-W.png',
    image2: 'EDe-M.png',
  },
  42: {
    name: 'Gia Rai',
    selfName: 'Gia-rai',
    otherName: 'Giơ Ray, Chơ Ray',
    localGroup: 'Chor, Hđrung, Aráp, Mthur, Tơbuân',
    region: 'Tây Nguyên',
    area: 'Gia Lai, Kon Tum, phía Bắc tỉnh Đắc Lắc và phía Tây tỉnh Phú Yên',
    population: '513.930',
    populationPercent: '0.534%',
    languageGroup: 'Mã Lai - Đa Đảo',
    languageFamily: 'Nam Đảo',
    shortHistory: 'Người Gia Rai sinh tụ từ lâu đời ở vùng núi Tây Nguyên. Họ sống dựa vào trồng trọt, có hệ thống quản lý và phân chia đất đai canh tác từ rất sớm. Ngày thường, đàn ông Gia Rai mặc áo chui đầu, đóng khố vải trắng kẻ sọc - gọi là "Toai". Ngày lễ họ mặc khố màu chàm, nhiều hoa văn rực rỡ, gọi là "Toai Kteh". Phụ nữ Gia Rai mặc áo chui đầu, cổ khoét cao, mở cúc ở đường bờ vai, có trang trí hoa văn ở chân gấu áo, ngang ngực, hai bên vai, nách và trên cánh tay áo.',
    image1: 'GiaRai-W.png',
    image2: 'GiaRai-M.png',
  },
  43: {
    name: 'Mạ',
    selfName: 'Mạ',
    otherName: 'Châu Mạ, Chô Mạ, Chê Mạ',
    localGroup: 'Mạ Ngăn, Mạ Xốp, Mạ Tô, Mạ Krung',
    region: 'Tây Nguyên',
    area: 'Chủ yếu ở tỉnh Lâm Đồng. Một số ở Đắc Nông, Đồng Nai, Bình Phước',
    population: '50.322',
    populationPercent: '0.052%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Đảo',
    shortHistory: 'Người Mạ sống chủ yếu bằng kinh tế rẫy đa canh, ngoài lúa họ còn trồng nhiều loại cây khác. Nghề đánh cá khá phổ biến. Nghề trồng bông dệt vải đặc biệt phát triển. Người Mạ rất điêu luyện trong việc sử dụng màu sắc khi dệt vải thổ cẩm. Mỗi màu vải được nhuộm từ một loại cây khác nhau. Hoa văn chủ yếu là dạng hình học. Phụ nữ mặc áo sát thân, không xẻ tà, cổ áo tròn thấp. Nam đóng khố, mặc áo chui đầu, vạt áo sau dài hơn vạt trước che kín mông.',
    image1: 'Ma-W.png',
    image2: 'Ma-M.png',
  },
  44: {
    name: 'Mnông',
    selfName: 'Mnông',
    otherName: '',
    localGroup: 'Mnông Gar, Mnông Nông, Mnông Chil, Mnông Kuênh, Mnông Rlâm, Mnông Preh, Mnông Prâng, Mnông Ðíp, Mnông Bhiêt, Mnông Sitô, Mnông Bu Ðâng, Mnông Bu Nor, Mnông Bu Ðêh…',
    region: 'Tây Nguyên',
    area: 'Tỉnh Đắc Nông, Đắc Lắc, Quảng Nam, Lâm Đồng và Quảng Bình',
    population: '127.334',
    populationPercent: '0.132%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Mnông sinh tụ lâu đời ở khu vực miền trung Tây Nguyên nước ta. Họ trồng lúa làm cây lương thực chính. Nghề đan mây tre, trồng bông dệt vải phát triển. Theo truyền thống, đàn ông và đàn bà Mnong đều ở trần. Đàn ông mặc khố, đàn bà quấn váy tấm. Khố người Mnong có ba loại, khố trắng cho người nghèo, khố đen cho người bình dân và khố hoa (vải nền đen có hoa bạc hoặc đồng và hạt cườm ngũ sắc) dành cho người giàu.',
    image1: 'Mnong-W.png',
    image2: 'Mnong-M.png',
  },
  45: {
    name: 'Rơ Măm',
    selfName: 'Rơ Măm',
    otherName: '',
    localGroup: '',
    region: 'Tây Nguyên',
    area: 'làng Le xã Mô Rai thuộc huyện Sa Thầy tỉnh Kon Tum',
    population: '639',
    populationPercent: '0.001%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Rơ Măm chủ yếu trồng lúa nếp trên nương rẫy. Họ từng có nghề dệt nhưng nay đã mai một. Đàn ông Rơ Măm ở trần đóng khố - thường khố có màu trắng của vải. Họ thường xăm kín lưng, nhất là người cao tuổi. Phụ nữ thường để tóc dài búi sau gáy. Họ mặc áo cộc tay vai thẳng, thân thẳng. Áo thường có màu sáng, các đường viền cổ và viền tay màu đỏ. Váy màu trắng của vải sợi bông, bốn mép có hoa văn trang trí màu đỏ.',
    image1: 'RoMam-W.png',
    image2: 'RoMam-M.png',
  },
  46: {
    name: 'Xơ Đăng',
    selfName: 'Xơ Đăng',
    otherName: 'Hđang, Kmrâng, Con lan, Brila',
    localGroup: 'Xơ Teng, Tơ Ðrá, Mnâm, Ca Dong, Ha Lăng, Tà Trĩ, Châu',
    region: 'Tây Nguyên',
    area: 'Tập trung ở tỉnh Kon Tum, số ít rải rác ở tỉnh Quảng Ngãi và Quảng Nam',
    population: '212.277',
    populationPercent: '0.221%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Xơ Đăng canh tác chủ yếu trên nương rẫy. Nhóm Mnâm biết trồng lúa nước, nhánh Ca Dong trồng quế còn nhánh Tơ Đrá phát triển nghề rèn. Cả năm nhóm đều có nghề dệt thổ cẩm phát triển. Trang phục của người Xơ Đăng chủ yếu có màu đen và màu chàm. Theo truyền thống, ngày thường nam giới Xơ Đăng cởi trần đóng khố. Vào các dịp lễ tết thì người nam quấn thêm một tấm vải quanh người, giống như chiến binh ra trận. Phụ nữ Xơ Đăng mặc áo chui đầu không tay, váy quấn và thêm khăn choàng vai.',
    image1: 'XoDang-W.png',
    image2: 'XoDang-M.png',
  },
  47: {
    name: 'Ba Na',
    selfName: 'Ba Na',
    otherName: 'Bơ Nâm, Roh, Kon Kđe, Ala Kông, Kpang Kông',
    localGroup: 'Rơ Ngao, Rơ Lơng (hay Y Lăng), Tơ Lô, Gơ Lar Krem',
    region: 'Tây Nguyên, Nam Trung Bộ',
    area: 'Gia Lai, Kon Tum, miền tây Bình Định, Phú Yên, Khánh Hòa',
    population: '286.910',
    populationPercent: '0.298%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Ba Na là một trong những dân tộc đông dân nhất và có ảnh hưởng lớn tới các yếu tố văn hóa, xã hội ở khu vực miền Trung nước ta. Đàn ông Ba Na thường ở trần, đóng khố đen có các sọc đỏ chạy dọc. Chỉ khi lễ hội hoặc trời lạnh họ mới mặc thêm áo cộc tay, chui đầu. Phụ nữ mặc váy đen, cũng kèm áo vuông chui đầu, có tay hoặc không tay. Trang phục của già làng và thầy cúng tương tự người dân nhưng nhiều hoa văn và nhiều màu đỏ hơn.',
    image1: 'BaNa-W.png',
    image2: 'BaNa-M.png',
  },
  48: {
    name: 'Gié Triêng',
    selfName: 'Gié Triêng',
    otherName: 'Cà Tang, Giang Rẫy',
    localGroup: 'Gié (Giẻ), Triêng (T’riêng), Ve, Bnoong (Mnoong)',
    region: 'Tây Nguyên, Nam Trung Bộ',
    area: 'Huyện Đắc Giây tỉnh Kon Tum, huyện Giằng, Phước Sơn, Trà My tỉnh Quảng Nam',
    population: '63.322',
    populationPercent: '0.066%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Giẻ Triêng có sở trường về đan lát, phát triển nghề dệt vải, một số khu vực có truyền thống đãi vàng sa khoáng và làm gốm. Phụ nữ Giẻ Triêng mặc váy ống dài sát nách, nền chàm, có hoa văn sọc đỏ ở đầu và chân váy. Loại váy này khá ít gặp ở các dân tộc thiểu số. Đàn ông đóng khố, ở trần, khi trời lạnh thì mặc thêm áo. Vào các dịp lễ, người Giẻ Triêng mặc thêm những tấm choàng rộng màu chàm phủ kín thân.',
    image1: 'GieTrieng-W.png',
    image2: 'GieTrieng-M.png',
  },
  49: {
    name: 'Hrê',
    selfName: 'Hrê',
    otherName: 'Chăm Rê, Chom, Thượng Ba Tơ, Mọi Luỹ, Mọi Sơn Phòng, Mọi Ðá Vách, Chăm Quảng Ngãi, Mọi Chòm, Rê, Màn Thạch Bích.',
    localGroup: '',
    region: 'Tây Nguyên, Nam Trung Bộ',
    area: 'Miền tây tỉnh Quảng Ngãi và tỉnh Bình Định, số ít ở tỉnh Kon Tum',
    population: '149.460',
    populationPercent: '0.155%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Hre xuất hiện từ rất lâu ở khu vực Trường Sơn - Tây Nguyên. Đa phần người dân sống bằng trồng lúa nước. Nghề thủ công chỉ có đan lát và dệt vải nhưng đã mai một. Ở trang phục của người Hre, có ba màu thường được sử dụng là màu đen, đỏ và trắng, trong đó màu đen là nền chủ đạo. Người Hre quan niệm màu đen là màu kín đáo và dịu dàng. Nữ mặc váy ống hai tầng. Nam cởi trần đóng khố, chít khăn, khi có lễ hội thì mặc áo.',
    image1: 'Hre-W.png',
    image2: 'Hre-M.png',
  },
  50: {
    name: 'Chơ ro',
    selfName: 'Chơ ro',
    otherName: 'Châu Ro, Dơ Ro, Chro, Thượng',
    localGroup: '',
    region: 'Đông Nam Bộ',
    area: 'Một số xã thuộc huyện Xuân Lộc và huyện Châu Thành, tỉnh Đồng Nai. Bà Rịa - Long Khánh',
    population: '29.520',
    populationPercent: '0.031%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: 'Người Chơ Ro cư trú từ lâu đời ở các vùng núi thấp Nam Đông Dương. Trang phục truyền thống của người Chơ Ro gồm váy dành cho nữ, khố dành cho nam giới. Xưa, cả đàn ông đàn bà đều để ngực trần, chỉ khi trời lạnh mới mặc áo chui đầu buộc dây. Từ khoảng những năm 50 của thế kỷ 20, trang phục truyền thống Chơ Ro bắt đầu mai một. Các bộ trang phục truyền thống chính gốc Chơ Ro đa phần đều đã cũ, thuộc về những người cao tuổi.',
    image1: 'ChoRo-W.png',
    image2: 'ChoRo-M.png',
  },
  51: {
    name: "X'Tiêng",
    selfName: "X'Tiêng",
    otherName: 'Xa Ðiêng hay Xa Chiêng',
    localGroup: 'Bù Lơ, Bù Ðek (Bù Ðêh), Bù Biêk',
    region: 'Đông Nam Bộ',
    area: 'Tỉnh Bình Phước, Tây Ninh và Đồng Nai',
    population: '100.752',
    populationPercent: '0.105%',
    languageGroup: 'Môn - Khơ Me',
    languageFamily: 'Nam Á',
    shortHistory: "Người Xtieng sống chủ yếu bằng trồng lúa, trên rẫy hoặc ruộng nước. Họ thường đựng đồ trong vỏ bầu khô được chế tác. Thông thường, đàn ông X'Tiêng đóng khố, cởi trần. Đàn bà mặc áo, quấn váy. Váy thường là loại váy dài quấn cao quá ngực, mép dưới phủ đến cổ chân hoặc váy ngắn quấn quanh eo, mặc cùng với áo.",
    image1: 'XTieng-W.png',
    image2: 'XTieng-M.png',
  },
  52: {
    name: "Khmer",
    selfName: "Khmer",
    otherName: "Cur, Cul, Cu Thổ, Việt gốc Miên, Khơ Me K’rôm",
    localGroup: 'Không có',
    region: 'Đồng bằng sông Cửu Long',
    area: 'Các tỉnh Nam Bộ: Trà Vinh, Sóc Trăng, Kiên Giang, An Giang, Cần Thơ, Vĩnh Long,…',
    population: '1.319.652',
    populationPercent: '1.372%',
    languageGroup: 'Môn - Khơ Me (Mon-Khmer)',
    languageFamily: 'Nam Á',
    shortHistory: "Văn hóa Khmer từng đóng vai trò chủ thể ở vùng đồng bằng sông Cửu Long giai đoạn trước thể kỷ XII. Họ là những cư dân nông nghiệp, có nghề trồng lúa nước với kỹ thuật khá hoàn thiện. Người Khmer còn có nghề đánh cá, dệt, làm chiếu, làm đường thốt nốt và làm gốm. Trước đây, ngày thường nam nữ Khmer đều mặc xà rông bằng lụa tơ tằm. Trang phục ngày lễ của phụ nữ Khmer gồm có áo tầm vông, váy Sămpết chôn Kpai cùng với khăn sbay quấn chéo người. Điểm đặc sắc ở trang phục Khmer là hoa văn sặc sỡ và hạt cườm, kim sa lấp lánh được sử dụng rất nhiều. Nam Khmer mặc áo ngắn, cổ cứng, xẻ ngực, giữa cài khuy.",
    image1: 'Khmer-W.png',
    image2: 'Khmer-M.png',
  },
  53: {
    name: "Hoa",
    selfName: "Hoa",
    otherName: 'Khách, Hán, Tàu',
    localGroup: 'Quảng Ðông, Quảng Tây, Hải Nam, Triều Châu, Phúc Kiến, Sang Phang, Xìa Phống, Thoòng Nhằn, Minh Hương, Hẹ…',
    region: 'Đông Nam Bộ, Đồng bằng sông Cửu Long',
    area: 'Tất cả 63 tỉnh, thành phố. Tập trung ở TP Hồ Chí Minh, Đồng Nai, Sóc Trăng, Kiên Giang, Bạc Liêu',
    population: '749.466',
    populationPercent: '0.779%',
    languageGroup: 'Hán',
    languageFamily: 'Hán-Tạng',
    shortHistory: 'Người Hoa di cư từ Trung Quốc vào Việt Nam vào nhiều giai đoạn, bắt đầu từ thế kỷ XVI đến nửa đầu thế kỷ XX. Người Hoa ở nông thôn sống dựa vào lúa nước, ở thành thị thì nhờ dịch vụ, buôn bán. Họ phát triển nghề gốm, làm giấy súc, làm nhang... Trang phục truyền thống của phụ nữ người Hoa là áo cổ viền cao, cài khuy bên, xẻ tà hoặc áo "sườn xám" ôm hông, xẻ tà. Nam giới mặc áo ngắn tên "xá xẩu", nút áo bằng vải, cài ở giữa.',
    image1: 'Hoa-W.png',
    image2: 'Hoa-M.png',
  },
  54: {
    name: "Chăm",
    selfName: "Chăm",
    otherName: 'Chàm, Chiêm, Chiêm Thành, Chăm Pa, Hời...',
    localGroup: 'Chăm Hroi, Chăm Poổng, Chà Và Ku, Chăm Châu Ðốc.',
    region: 'Đông Nam Bộ, Đồng bằng sông Cửu Long, Nam Trung Bộ',
    area: 'Ninh Thuận, Bình Thuận, Tây Ninh, An Giang, Đồng Nai, TP HCM',
    population: '178.948',
    populationPercent: '0.186%',
    languageGroup: 'Mã Lai - Đa Đảo',
    languageFamily: 'Nam Đảo',
    shortHistory: "Người Chăm là cư dân bản địa khu vực duyên hải Nam Trung Bộ. Nếu chia theo tôn giáo, ở Việt Nam có bốn nhóm Chăm chính, gồm Chăm Bà La Môn theo Bà La Môn giáo, Chăm Bà Ni, Chăm Islam. Nhóm thứ tư là Chăm Kroi không theo tôn giáo nào cả. Nam nữ người Chăm đều quấn váy tấm. Nam mặc áo cánh xẻ ngực cài khuy, nữ mặc áo dài chui đầu.",
    image1: 'Cham-W.png',
    image2: 'Cham-M.png',
  },
};

const EthnicDetailPage = () => {
  const { id } = useParams(); // Lấy id từ URL params

  const groupInfo = ethnicData[id];

  if (!groupInfo) {
    return <div>Không tìm thấy thông tin dân tộc</div>;
  }

  return (
    <div>
      <MultiLevelNavbar />
      <EthnicGroupInfo groupInfo={groupInfo} />
      <Footer />
    </div>
  );
};

export default EthnicDetailPage;
